remote_id = '489474655'
kb_layout_type = ''
size = [
    0,
    0,
    0,
    0,
]
fav = []

[options]
remote-menubar-drag-right = '1.0'
remote-menubar-drag-left = '0.0'

[ui_flutter]
peer-sorting = 'Remote ID'
wm_RemoteDesktop = '{"width":1300.0,"height":740.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":true,"isFullscreen":false}'
wm_Main = '{"width":800.0,"height":600.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":false,"isFullscreen":false}'
