services:
  gitlab:
    image: gitlab/gitlab-ee:18.6.0-ee.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        # access by https://localhost
        external_url 'http://my-pc/gitlab'
    ports:
      - '22:22'
      # forward by nginx
      #- '80:80'
      #- '443:443'
    volumes:
      - '$HOME/Services/gitlab/config:/etc/gitlab'
      - '$HOME/Services/gitlab/logs:/var/log/gitlab'
      - '$HOME/Services/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - service-net
  nginx:
    image: nginx:1.29.3
    container_name: nginx
    restart: always
    ports:
      - "443:443"    # http
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro   # 重点：只挂一个主配置文件
      - ../certs/server.crt:/etc/nginx/server.crt:ro
      - ../certs/server.key:/etc/nginx/server.key:ro
    depends_on:
      - gitlab
    networks:
      - service-net

networks:
  service-net:
    driver: bridge
