services:
  gitlab:
    image: gitlab/gitlab-ee:18.6.0-ee.0
    container_name: gitlab
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        # access by https://localhost
        external_url 'https://localhost'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$HOME/Services/gitlab/config:/etc/gitlab'
      - '$HOME/Services/gitlab/logs:/var/log/gitlab'
      - '$HOME/Services/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
