enc_id = '009ve3yW36/gxpt5BhfktyDVIAO9Lx3/Y='
password = ''
salt = 'w3ze54'
key_pair = [
    [
    181,
    207,
    191,
    36,
    158,
    183,
    218,
    68,
    86,
    244,
    255,
    66,
    57,
    137,
    240,
    81,
    117,
    71,
    175,
    221,
    3,
    251,
    118,
    76,
    168,
    150,
    195,
    42,
    125,
    97,
    225,
    247,
    178,
    53,
    54,
    49,
    0,
    109,
    127,
    235,
    26,
    130,
    193,
    105,
    57,
    84,
    1,
    94,
    95,
    42,
    252,
    131,
    239,
    39,
    217,
    169,
    154,
    223,
    47,
    253,
    214,
    215,
    133,
    90,
],
    [
    178,
    53,
    54,
    49,
    0,
    109,
    127,
    235,
    26,
    130,
    193,
    105,
    57,
    84,
    1,
    94,
    95,
    42,
    252,
    131,
    239,
    39,
    217,
    169,
    154,
    223,
    47,
    253,
    214,
    215,
    133,
    90,
],
]
key_confirmed = true

[keys_confirmed]
rs-ny = true
