name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: shylockhg/opensuse:latest

    steps:
    - uses: actions/checkout@v4
    - name: test setup
      run: |
        cp -r . ~/dotfiles
        cd ~/dotfiles
        ./setup.sh
